name: "eInk Updater"
description: "Refresh eInk diplays in the house"
version: "1.0.0"
slug: "eink_slug"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
devices:
  - /config/www/pics
host_dbus: true
map:
  - config:rw
options:
  liquor: false
  name: "world"
  key: 2017
schema:
  liquor: bool
  name: str
  year: int
