name: "eInk Updater"
description: "Refresh eInk diplays in the house"
version: "1.0.0"
slug: "eink_slug"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
devices:
  - /config/www/pics
host_dbus: true
homeassistant_api: true
map:
  - config:rw
services:
  - mqtt:need
options:
  username: "MQTT Username"
  password: "MQTT Password"
  liquor: false
  name: "world"
  key: 2017
  amount: 1
  width: 1872
  height: 1404
schema:
  username: str
  password: str
  liquor: bool
  name: str
  key: int
  amount: int
  width: int
  height: int
